"""auto update

Revision ID: 374063b850f9
Revises: 
Create Date: 2026-07-27 14:54:35.197298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '374063b850f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('guide_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=True),
    sa.Column('payment_session_id', sa.String(length=300), nullable=True),
    sa.Column('guide_paid', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_guide_id'), 'bookings', ['guide_id'], unique=False)
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.create_index(op.f('ix_bookings_payment_session_id'), 'bookings', ['payment_session_id'], unique=False)
    op.create_index(op.f('ix_bookings_tour_id'), 'bookings', ['tour_id'], unique=False)
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_table('guides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('bio', sa.String(length=2000), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('languages', sa.String(length=500), nullable=False),
    sa.Column('specialties', sa.String(length=500), nullable=True),
    sa.Column('cities', sa.String(length=500), nullable=False),
    sa.Column('paypal_email', sa.String(length=200), nullable=False),
    sa.Column('rating', sa.Float(), server_default='0', nullable=True),
    sa.Column('total_reviews', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guides_id'), 'guides', ['id'], unique=False)
    op.create_index(op.f('ix_guides_user_id'), 'guides', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.String(length=5000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_booking_id'), 'messages', ['booking_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_table('tours',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('duration_hours', sa.Float(), nullable=False),
    sa.Column('price_ils', sa.Float(), nullable=False),
    sa.Column('max_participants', sa.Integer(), server_default='10', nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tours_guide_id'), 'tours', ['guide_id'], unique=False)
    op.create_index(op.f('ix_tours_id'), 'tours', ['id'], unique=False)
    op.create_index(op.f('ix_tours_user_id'), 'tours', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tours_user_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_id'), table_name='tours')
    op.drop_index(op.f('ix_tours_guide_id'), table_name='tours')
    op.drop_table('tours')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_booking_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_guides_user_id'), table_name='guides')
    op.drop_index(op.f('ix_guides_id'), table_name='guides')
    op.drop_table('guides')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_tour_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_payment_session_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_guide_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###