"""auto update

Revision ID: dc2e5451e644
Revises: f9372c17a09c
Create Date: 2026-08-14 11:29:14.261461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2e5451e644'
down_revision: Union[str, Sequence[str], None] = 'f9372c17a09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_languages_id'), 'app_languages', ['id'], unique=False)
    op.create_table('dashboard_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('subtitle', sa.String(), nullable=True),
    sa.Column('highlight', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_modules_id'), 'dashboard_modules', ['id'], unique=False)
    op.create_table('onboarding_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_cards_id'), 'onboarding_cards', ['id'], unique=False)
    op.create_table('quick_access_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('icon', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quick_access_items_id'), 'quick_access_items', ['id'], unique=False)
    op.create_table('shabbat_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('parasha', sa.String(), nullable=False),
    sa.Column('candle_lighting', sa.String(), nullable=False),
    sa.Column('havdalah', sa.String(), nullable=False),
    sa.Column('date_friday', sa.String(), nullable=True),
    sa.Column('hebrew_date', sa.String(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shabbat_times_id'), 'shabbat_times', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shabbat_times_id'), table_name='shabbat_times')
    op.drop_table('shabbat_times')
    op.drop_index(op.f('ix_quick_access_items_id'), table_name='quick_access_items')
    op.drop_table('quick_access_items')
    op.drop_index(op.f('ix_onboarding_cards_id'), table_name='onboarding_cards')
    op.drop_table('onboarding_cards')
    op.drop_index(op.f('ix_dashboard_modules_id'), table_name='dashboard_modules')
    op.drop_table('dashboard_modules')
    op.drop_index(op.f('ix_app_languages_id'), table_name='app_languages')
    op.drop_table('app_languages')
    # ### end Alembic commands ###