"""auto update

Revision ID: f9372c17a09c
Revises: 5579b8601e1f
Create Date: 2026-08-13 11:43:49.768620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9372c17a09c'
down_revision: Union[str, Sequence[str], None] = '5579b8601e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured_restaurants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('price_level', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('featured_section', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_featured_restaurants_id'), 'featured_restaurants', ['id'], unique=False)
    op.create_table('rental_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('flag', sa.String(), nullable=True),
    sa.Column('price_from', sa.Float(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('locations', sa.String(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rental_companies_id'), 'rental_companies', ['id'], unique=False)
    op.create_table('taxi_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('distance_range', sa.String(), nullable=False),
    sa.Column('distance_label', sa.String(), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=False),
    sa.Column('price_max', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxi_info_id'), 'taxi_info', ['id'], unique=False)
    op.drop_column('shopping_brands', 'short_description')
    op.drop_column('shopping_brands', 'price_level')
    op.drop_column('shopping_brands', 'online_store_url')
    op.drop_column('shopping_brands', 'website_url')
    op.drop_column('shopping_brands', 'category_ids')
    op.drop_column('shopping_brands', 'sponsored')
    op.drop_column('shopping_brands', 'slug')
    op.drop_column('shopping_brands', 'verification_status')
    op.drop_column('shopping_brands', 'sustainability_tags')
    op.drop_column('shopping_brands', 'instagram_url')
    op.drop_column('shopping_brands', 'israeli_brand')
    op.drop_column('shopping_brands', 'style_tags')
    op.drop_column('shopping_offers', 'end_date')
    op.drop_column('shopping_offers', 'status')
    op.drop_column('shopping_offers', 'terms')
    op.drop_column('shopping_offers', 'sponsored')
    op.drop_column('shopping_offers', 'city_restrictions')
    op.drop_column('shopping_offers', 'destination_url')
    op.drop_column('shopping_offers', 'discount_amount')
    op.drop_column('shopping_offers', 'currency')
    op.drop_column('shopping_offers', 'in_store_only')
    op.drop_column('shopping_offers', 'start_date')
    op.drop_column('shopping_offers', 'verified')
    op.drop_column('shopping_offers', 'offer_type')
    op.drop_column('shopping_offers', 'online_only')
    op.drop_column('shopping_offers', 'affiliate_url')
    op.drop_column('shopping_stores', 'description')
    op.drop_column('shopping_stores', 'opening_hours')
    op.drop_column('shopping_stores', 'website_url')
    op.drop_column('shopping_stores', 'store_type')
    op.drop_column('shopping_stores', 'shopping_center_id')
    op.drop_column('shopping_stores', 'languages_spoken')
    op.drop_column('shopping_stores', 'slug')
    op.drop_column('shopping_stores', 'wheelchair_accessible')
    op.drop_column('shopping_stores', 'neighborhood')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_stores', sa.Column('neighborhood', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('wheelchair_accessible', sa.VARCHAR(), server_default=sa.text("'unknown'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('languages_spoken', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('shopping_center_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('store_type', sa.VARCHAR(), server_default=sa.text("'regular'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('opening_hours', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_stores', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('affiliate_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('online_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('offer_type', sa.VARCHAR(), server_default=sa.text("'percentage_discount'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('start_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('in_store_only', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('currency', sa.VARCHAR(), server_default=sa.text("'ILS'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('discount_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('destination_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('city_restrictions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('sponsored', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('terms', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shopping_offers', sa.Column('end_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('style_tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('israeli_brand', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('instagram_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('sustainability_tags', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('verification_status', sa.VARCHAR(), server_default=sa.text("'verified'::character varying"), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('sponsored', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('category_ids', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('online_store_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('price_level', sa.INTEGER(), server_default=sa.text('2'), autoincrement=False, nullable=True))
    op.add_column('shopping_brands', sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_taxi_info_id'), table_name='taxi_info')
    op.drop_table('taxi_info')
    op.drop_index(op.f('ix_rental_companies_id'), table_name='rental_companies')
    op.drop_table('rental_companies')
    op.drop_index(op.f('ix_featured_restaurants_id'), table_name='featured_restaurants')
    op.drop_table('featured_restaurants')
    # ### end Alembic commands ###